export const greetings = {
    normal: [
    "Nice!",
    "Finally!",
    "Good Job!",
    "Incredible!",
    "Noice!",
    "Wowza!",
    "Woot Woot!",
    "That's LITERALLY awesome!",
    "Groovy!",
    "Righteous!",
    "Copacetic!",
    "Nifty!",
    "Quite a wordsmith there!",
    "You da best!",
    "Brilliant!",
    "Smart!",
    "Some Brain Power!",
    "Unnn-Believable",
    "Amazing!",
    "High Roller!",
    "Splendiferous!",
    "You're on fire!",
    "Scrabble ninja!",
    "Word wizard!",
    "Dictionary master!",
    "That's bananas!",
    "Spectacular!",
    "Smooth move!",
    "Crushing it!",
    "Absolutely smashing!",
    "You're a legend!",
    "Outstanding!",
    "Phenomenal!",
    "Top notch!",
    "Mic drop!",
    "Chef's kiss!",
    "Rad!",
    "Bodacious!",
    "Tubular!",
    "Swag!",
    "On point!"
    ], 
    passExchange: [
        "Ow Ow Ow!",
        "Better Luck Next Time!",
        "It sucks, I know!",
        "OH MY GOD!",
        "Ouch!",
        "Bad Letters, Huh?",
        "Yikes on bikes!",
        "Really? That's your move?",
        "Bold strategy, Cotton!",
        "Giving up already?",
        "I'm sure that was necessary...",
        "Taking the easy way out, huh?",
        "Quitter!",
        "Even a monkey could've played something!",
        "Was it something I said?",
        "Your loss, literally!",
        "The dictionary is your friend, you know!",
        "Those tiles weren't THAT bad...",
        "Chicken!",
        "Shakespeare would be disappointed!",
        "Not your finest moment!",
    ]

}

export const AI_LIST = [
    "AI Lily",
    "AI Kira",
    "AI Jasmine",
    "AI Kashmir",
    "AI Dylan",
    "AI Sienna",
    "AI Sassy",
    "AI Tortoise",
    'AI Sahara'
]
